name: Build and upload notation binaries

on:
  push:
    branches: [ test_action ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Make
      run: make build
      
    - name: Upload
      uses: actions/upload-artifact@v2.3.1
      with:
        name: notation binaries
        path: bin/


  
